syntax = "proto3";
package cosmos.nft;

import "google/protobuf/any.proto";
import "cosmos/base/query/v1beta1/pagination.proto";
import "google/api/annotations.proto";
import "gogoproto/gogo.proto";
import "cosmos/base/v1beta1/coin.proto";

option go_package = "github.com/cosmos/cosmos-sdk/x/nft/types";

// NFT defines the NFT.
message NFT {
  string address = 1;

  string owner = 2;

  string uri = 3;

  cosmos.base.v1beta1.Coin reward_per_period = 4 [(gogoproto.nullable) = false];

  int64 vesting_periods_count  = 5;

  cosmos.base.v1beta1.Coin available_to_withdraw = 6 [(gogoproto.nullable) = false];

  int64 last_vesting_block = 7;

  string denom = 8;

  int64 start_vesting_block = 9;
}

message Owner {
  string address = 1;
  string nft_address = 2;
}

