syntax = "proto3";
package cosmos.nft;

import "gogoproto/gogo.proto";
import "cosmos/nft/nft.proto";

option go_package = "github.com/cosmos/cosmos-sdk/x/nft/types";

// Params defines the parameters for the module.
message Params {
  string module_admin = 1;
  string bond_denom = 2;
  string prefix = 3;
  uint64 nft_sequence = 4;
  int64 vesting_time = 5;
  int64 vesting_period = 6;
  uint64 vesting_periods_count = 7;
  string nft_cost = 8;
  uint64 batch_size = 9;
  uint64 batch_index = 10;
}
