// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/nft/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	ModuleAdmin         string `protobuf:"bytes,1,opt,name=module_admin,json=moduleAdmin,proto3" json:"module_admin,omitempty"`
	BondDenom           string `protobuf:"bytes,2,opt,name=bond_denom,json=bondDenom,proto3" json:"bond_denom,omitempty"`
	Prefix              string `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	NftSequence         uint64 `protobuf:"varint,4,opt,name=nft_sequence,json=nftSequence,proto3" json:"nft_sequence,omitempty"`
	VestingTime         int64  `protobuf:"varint,5,opt,name=vesting_time,json=vestingTime,proto3" json:"vesting_time,omitempty"`
	VestingPeriod       int64  `protobuf:"varint,6,opt,name=vesting_period,json=vestingPeriod,proto3" json:"vesting_period,omitempty"`
	VestingPeriodsCount uint64 `protobuf:"varint,7,opt,name=vesting_periods_count,json=vestingPeriodsCount,proto3" json:"vesting_periods_count,omitempty"`
	NftCost             uint64 `protobuf:"varint,8,opt,name=nft_cost,json=nftCost,proto3" json:"nft_cost,omitempty"`
	BatchSize           uint64 `protobuf:"varint,9,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	BatchIndex          uint64 `protobuf:"varint,10,opt,name=batch_index,json=batchIndex,proto3" json:"batch_index,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e3941e289c0c22d, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetModuleAdmin() string {
	if m != nil {
		return m.ModuleAdmin
	}
	return ""
}

func (m *Params) GetBondDenom() string {
	if m != nil {
		return m.BondDenom
	}
	return ""
}

func (m *Params) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *Params) GetNftSequence() uint64 {
	if m != nil {
		return m.NftSequence
	}
	return 0
}

func (m *Params) GetVestingTime() int64 {
	if m != nil {
		return m.VestingTime
	}
	return 0
}

func (m *Params) GetVestingPeriod() int64 {
	if m != nil {
		return m.VestingPeriod
	}
	return 0
}

func (m *Params) GetVestingPeriodsCount() uint64 {
	if m != nil {
		return m.VestingPeriodsCount
	}
	return 0
}

func (m *Params) GetNftCost() uint64 {
	if m != nil {
		return m.NftCost
	}
	return 0
}

func (m *Params) GetBatchSize() uint64 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

func (m *Params) GetBatchIndex() uint64 {
	if m != nil {
		return m.BatchIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "cosmos.nft.Params")
}

func init() { proto.RegisterFile("cosmos/nft/params.proto", fileDescriptor_9e3941e289c0c22d) }

var fileDescriptor_9e3941e289c0c22d = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x41, 0x4f, 0xf2, 0x30,
	0x18, 0xc7, 0x19, 0xf0, 0x0e, 0xd6, 0xbd, 0x7a, 0xa8, 0xa8, 0x95, 0xc4, 0x89, 0x26, 0x26, 0xbb,
	0xc8, 0x12, 0xfd, 0x04, 0x82, 0x17, 0x6f, 0x04, 0x3c, 0x79, 0x59, 0xc6, 0xd6, 0x8d, 0x46, 0xdb,
	0xce, 0xf5, 0x99, 0x41, 0x3e, 0x85, 0x1f, 0xcb, 0x23, 0x47, 0x4f, 0xc6, 0xc0, 0x17, 0x31, 0xed,
	0x66, 0x22, 0xa7, 0xb6, 0xbf, 0xff, 0xef, 0x79, 0xda, 0xe6, 0x41, 0xc7, 0xb1, 0x54, 0x5c, 0xaa,
	0x40, 0xa4, 0x10, 0xe4, 0x51, 0x11, 0x71, 0x35, 0xcc, 0x0b, 0x09, 0x12, 0xa3, 0x2a, 0x18, 0x8a,
	0x14, 0xfa, 0xbd, 0x4c, 0x66, 0xd2, 0xe0, 0x40, 0xef, 0x2a, 0xa3, 0xdf, 0xfb, 0x53, 0x2a, 0x52,
	0xa8, 0xe8, 0xc5, 0x57, 0x13, 0xd9, 0x13, 0xd3, 0x08, 0x9f, 0xa3, 0xff, 0x5c, 0x26, 0xe5, 0x33,
	0x0d, 0xa3, 0x84, 0x33, 0x41, 0xac, 0x81, 0xe5, 0x3b, 0x53, 0xb7, 0x62, 0xb7, 0x1a, 0xe1, 0x53,
	0x84, 0xe6, 0x52, 0x24, 0x61, 0x42, 0x85, 0xe4, 0xa4, 0x69, 0x04, 0x47, 0x93, 0x3b, 0x0d, 0xf0,
	0x11, 0xb2, 0xf3, 0x82, 0xa6, 0x6c, 0x49, 0x5a, 0x26, 0xaa, 0x4f, 0xba, 0xb3, 0x48, 0x21, 0x54,
	0xf4, 0xa5, 0xa4, 0x22, 0xa6, 0xa4, 0x3d, 0xb0, 0xfc, 0xf6, 0xd4, 0x15, 0x29, 0xcc, 0x6a, 0xa4,
	0x95, 0x57, 0xaa, 0x80, 0x89, 0x2c, 0x04, 0xc6, 0x29, 0xf9, 0x37, 0xb0, 0xfc, 0xd6, 0xd4, 0xad,
	0xd9, 0x03, 0xe3, 0x14, 0x5f, 0xa2, 0xfd, 0x5f, 0x25, 0xa7, 0x05, 0x93, 0x09, 0xb1, 0x8d, 0xb4,
	0x57, 0xd3, 0x89, 0x81, 0xf8, 0x1a, 0x1d, 0xee, 0x6a, 0x2a, 0x8c, 0x65, 0x29, 0x80, 0x74, 0xcc,
	0xad, 0x07, 0x3b, 0xb6, 0x1a, 0xeb, 0x08, 0x9f, 0xa0, 0xae, 0x7e, 0x60, 0x2c, 0x15, 0x90, 0xae,
	0xd1, 0x3a, 0x22, 0x85, 0xb1, 0x54, 0x60, 0xbe, 0x1c, 0x41, 0xbc, 0x08, 0x15, 0x5b, 0x51, 0xe2,
	0x98, 0xd0, 0x31, 0x64, 0xc6, 0x56, 0x14, 0x9f, 0x21, 0xb7, 0x8a, 0x99, 0x48, 0xe8, 0x92, 0x20,
	0x93, 0x57, 0x15, 0xf7, 0x9a, 0x8c, 0x46, 0x1f, 0x1b, 0xcf, 0x5a, 0x6f, 0x3c, 0xeb, 0x7b, 0xe3,
	0x59, 0xef, 0x5b, 0xaf, 0xb1, 0xde, 0x7a, 0x8d, 0xcf, 0xad, 0xd7, 0x78, 0xf4, 0x33, 0x06, 0x8b,
	0x72, 0x3e, 0x8c, 0x25, 0x0f, 0xea, 0xd9, 0x54, 0xcb, 0x95, 0x4a, 0x9e, 0x82, 0xa5, 0x19, 0x14,
	0xbc, 0xe5, 0x54, 0xcd, 0x6d, 0x33, 0xab, 0x9b, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x26, 0xab,
	0x27, 0x03, 0xfe, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BatchIndex != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BatchIndex))
		i--
		dAtA[i] = 0x50
	}
	if m.BatchSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BatchSize))
		i--
		dAtA[i] = 0x48
	}
	if m.NftCost != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.NftCost))
		i--
		dAtA[i] = 0x40
	}
	if m.VestingPeriodsCount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.VestingPeriodsCount))
		i--
		dAtA[i] = 0x38
	}
	if m.VestingPeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.VestingPeriod))
		i--
		dAtA[i] = 0x30
	}
	if m.VestingTime != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.VestingTime))
		i--
		dAtA[i] = 0x28
	}
	if m.NftSequence != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.NftSequence))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Prefix) > 0 {
		i -= len(m.Prefix)
		copy(dAtA[i:], m.Prefix)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Prefix)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BondDenom) > 0 {
		i -= len(m.BondDenom)
		copy(dAtA[i:], m.BondDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.BondDenom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ModuleAdmin) > 0 {
		i -= len(m.ModuleAdmin)
		copy(dAtA[i:], m.ModuleAdmin)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ModuleAdmin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModuleAdmin)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.BondDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.Prefix)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.NftSequence != 0 {
		n += 1 + sovParams(uint64(m.NftSequence))
	}
	if m.VestingTime != 0 {
		n += 1 + sovParams(uint64(m.VestingTime))
	}
	if m.VestingPeriod != 0 {
		n += 1 + sovParams(uint64(m.VestingPeriod))
	}
	if m.VestingPeriodsCount != 0 {
		n += 1 + sovParams(uint64(m.VestingPeriodsCount))
	}
	if m.NftCost != 0 {
		n += 1 + sovParams(uint64(m.NftCost))
	}
	if m.BatchSize != 0 {
		n += 1 + sovParams(uint64(m.BatchSize))
	}
	if m.BatchIndex != 0 {
		n += 1 + sovParams(uint64(m.BatchIndex))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModuleAdmin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModuleAdmin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BondDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prefix", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Prefix = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftSequence", wireType)
			}
			m.NftSequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NftSequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingTime", wireType)
			}
			m.VestingTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VestingTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingPeriod", wireType)
			}
			m.VestingPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VestingPeriod |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingPeriodsCount", wireType)
			}
			m.VestingPeriodsCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VestingPeriodsCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftCost", wireType)
			}
			m.NftCost = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NftCost |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchSize", wireType)
			}
			m.BatchSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BatchSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchIndex", wireType)
			}
			m.BatchIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BatchIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
